# Generated by Django 3.2.5 on 2022-01-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
