# Generated by Django 3.2.5 on 2022-02-24 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20220222_2142'),
        ('events', '0002_event_domain_of_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member'),
        ),
        migrations.AddField(
            model_name='event',
            name='organisers',
            field=models.ManyToManyField(blank=True, related_name='Organising_Members', to='members.Member'),
        ),
    ]
