# Generated by Django 3.2.5 on 2022-01-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='reg_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
