# Generated by Django 3.2.5 on 2022-03-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20220224_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='whatsapp_no',
            field=models.CharField(max_length=15),
        ),
    ]
