# Generated by Django 3.2.5 on 2022-01-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventregistration_reg_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='whatsapp_no',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
