# Generated by Django 3.2.5 on 2022-04-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='decription',
            field=models.TextField(null=True),
        ),
    ]
