# Generated by Django 3.2.5 on 2022-04-08 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_certificate_decription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='decription',
            new_name='description',
        ),
    ]
