# Generated by Django 3.2.5 on 2022-04-08 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_rename_decription_certificate_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='events',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
    ]
