# Generated by Django 3.2.5 on 2021-11-07 08:00

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=django_mysql.models.ListCharField(models.CharField(max_length=40), max_length=1050, null=True, size=20),
        ),
    ]
