# Generated by Django 3.2.5 on 2022-02-20 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='related_documents',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Project_Document', to='projects.document'),
        ),
    ]
