# Generated by Django 3.2.5 on 2022-02-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_rename_domain_member_domain_expertise'),
        ('projects', '0003_project_related_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='visible_to',
            field=models.ManyToManyField(blank=True, related_name='Visible_To', to='members.Member'),
        ),
    ]
