# Generated by Django 3.2.5 on 2022-02-21 11:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0004_document_visible_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='visible_to',
            field=models.ManyToManyField(blank=True, related_name='Visible_To', to=settings.AUTH_USER_MODEL),
        ),
    ]
