# Generated by Django 3.2.5 on 2022-02-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_document_visible_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='visibility',
            field=models.CharField(blank=True, choices=[('PRIVATE', 'Private'), ('PUBLIC', 'Public'), ('ONLY-MEMBERS', 'Only-Members')], max_length=20, null=True),
        ),
    ]
