# Generated by Django 3.2.5 on 2022-02-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20220222_2142'),
        ('projects', '0008_project_domain_of_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contributor',
            field=models.ManyToManyField(blank=True, related_name='Project_contributors', to='members.Member'),
        ),
        migrations.AddField(
            model_name='project',
            name='documents_of_project',
            field=models.ManyToManyField(blank=True, related_name='Project_related_docs', to='projects.Document'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_Team',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Stopped', 'Stopped')], default='Ongoing', max_length=20, null=True),
        ),
    ]
