# Generated by Django 3.2.5 on 2022-02-24 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_auto_20220224_2105'),
        ('projects', '0009_auto_20220224_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='domain_of_project',
        ),
        migrations.AddField(
            model_name='project',
            name='domain_of_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Domain_of_Projects', to='courses.domain'),
        ),
    ]
