# Generated by Django 3.2.5 on 2022-02-16 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_rename_domain_member_domain_expertise'),
        ('events', '0001_initial'),
        ('projects', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='home_page_display',
            field=models.CharField(blank=True, choices=[('Featured', 'Featured'), ('Exclusive', 'Exclusive')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Draft', 'Draft'), ('Rejected', 'Rejected'), ('Published', 'Published')], default='Draft', max_length=20),
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3000)),
                ('icon', models.CharField(choices=[('A', 'a'), ('B', 'b')], max_length=100)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('detailed_description', models.TextField(blank=True, null=True)),
                ('domain_lead', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='members.member')),
                ('events', models.ManyToManyField(blank=True, to='events.Event')),
                ('projects', models.ManyToManyField(blank=True, to='projects.Project')),
                ('track', models.ManyToManyField(blank=True, to='courses.Track')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='domain',
            field=models.ManyToManyField(blank=True, to='courses.Domain'),
        ),
    ]
