# Generated by Django 3.2.5 on 2022-02-19 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_rename_domain_member_domain_expertise'),
        ('courses', '0006_alter_article_home_page_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Domain_creator', to='members.member'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Draft', 'Draft'), ('Published', 'Published'), ('Created', 'Created')], default='Draft', max_length=20),
        ),
    ]
