# Generated by Django 3.2.5 on 2022-02-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20220220_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Published', 'Published'), ('Created', 'Created'), ('Draft', 'Draft')], default='Draft', max_length=20),
        ),
    ]
