# Generated by Django 3.2.5 on 2021-11-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Draft', 'Draft'), ('Published', 'Published'), ('Rejected', 'Rejected')], default='Draft', max_length=20),
        ),
    ]
