# Generated by Django 3.2.5 on 2021-11-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Draft', 'Draft'), ('Created', 'Created'), ('Published', 'Published')], default='Draft', max_length=20),
        ),
    ]
