# Generated by Django 3.2.5 on 2022-02-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20220221_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Draft', 'Draft'), ('Published', 'Published'), ('Created', 'Created')], default='Draft', max_length=20),
        ),
    ]
