# Generated by Django 3.2.5 on 2021-11-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20211107_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Published', 'Published'), ('Draft', 'Draft'), ('Created', 'Created')], default='Draft', max_length=20),
        ),
    ]
