# Generated by Django 3.2.5 on 2021-11-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_article_home_page_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Published', 'Published'), ('Rejected', 'Rejected'), ('Draft', 'Draft')], default='Draft', max_length=20),
        ),
    ]
