# Generated by Django 3.2.5 on 2022-03-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_auto_20220224_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='home_page_display',
            field=models.CharField(blank=True, choices=[('Featured', 'Featured'), ('Exclusive', 'Exclusive')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Created', 'Created'), ('Published', 'Published'), ('Draft', 'Draft')], default='Draft', max_length=20),
        ),
    ]
