# Generated by Django 3.2.5 on 2022-04-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_auto_20220309_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Created', 'Created'), ('Draft', 'Draft'), ('Published', 'Published')], default='Draft', max_length=20),
        ),
    ]
