# Generated by Django 3.2.5 on 2022-01-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_auto_20220123_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Rejected', 'Rejected'), ('Created', 'Created')], default='Draft', max_length=20),
        ),
    ]
