# Generated by Django 3.2.5 on 2022-02-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_auto_20220130_1708'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic',
            new_name='Tag',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='topic',
            new_name='Tag',
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Android', 'Android'), ('Web', 'Web'), ('Backend', 'Backend'), ('ML/AI', 'ML/AI'), ('UI/UX', 'UI/UX'), ('AR/VR', 'AR/VR'), ('CP', 'CP')], max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='home_page_display',
            field=models.CharField(blank=True, choices=[('Featured', 'Featured'), ('Exclusive', 'Exclusive')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Draft', 'Draft'), ('Published', 'Published'), ('Rejected', 'Rejected')], default='Draft', max_length=20),
        ),
    ]
