# Generated by Django 3.2.5 on 2022-02-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_auto_20220204_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Rejected', 'Rejected'), ('Created', 'Created'), ('Published', 'Published')], default='Draft', max_length=20),
        ),
    ]
