# Generated by Django 3.2.5 on 2022-02-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_auto_20220204_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='home_page_display',
            field=models.CharField(blank=True, choices=[('Exclusive', 'Exclusive'), ('Featured', 'Featured')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('Published', 'Published'), ('Created', 'Created'), ('Rejected', 'Rejected'), ('Draft', 'Draft')], default='Draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tags', to='courses.Tag'),
        ),
    ]
