# Generated by Django 3.2.5 on 2022-02-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_auto_20220204_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Rejected', 'Rejected'), ('Created', 'Created')], default='Draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tags', to='courses.Tag'),
        ),
    ]
