# Generated by Django 3.2.5 on 2022-02-04 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_auto_20220203_2348'),
        ('courses', '0026_auto_20220204_1947'),
        ('courses', '0031_auto_20220204_2213'),
    ]

    operations = [
    ]
