# Generated by Django 3.2.5 on 2022-02-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0035_alter_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Published', 'Published'), ('Created', 'Created'), ('Draft', 'Draft')], default='Draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='courses.Tag'),
        ),
    ]
