# Generated by Django 3.2.5 on 2022-02-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0038_auto_20220205_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='banner_image',
            field=models.ImageField(blank=True, default='article_banner_default.jpg', null=True, upload_to='ArticleBannerPics'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='article_default.jpg', upload_to='ArticlePics'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('Published', 'Published'), ('Created', 'Created'), ('Draft', 'Draft'), ('Rejected', 'Rejected')], default='Draft', max_length=20),
        ),
    ]
