# Generated by Django 3.2.5 on 2022-02-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0040_auto_20220205_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='articles',
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('Published', 'Published'), ('Created', 'Created'), ('Rejected', 'Rejected'), ('Draft', 'Draft')], default='Draft', max_length=20),
        ),
    ]
