# Generated by Django 3.2.5 on 2022-02-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0042_auto_20220205_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='courses.Tag'),
        ),
        migrations.AlterField(
            model_name='article',
            name='home_page_display',
            field=models.CharField(blank=True, choices=[('Featured', 'Featured'), ('Exclusive', 'Exclusive')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Created', 'Created'), ('Rejected', 'Rejected'), ('Published', 'Published')], default='Draft', max_length=20),
        ),
    ]
