# Generated by Django 3.2.5 on 2022-02-16 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='domain',
            new_name='domain_expertise',
        ),
    ]
