# Generated by Django 3.2.5 on 2022-02-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20220222_2048'),
        ('members', '0002_rename_domain_member_domain_expertise'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='New_domain_expertise',
            field=models.ManyToManyField(blank=True, related_name='DOMAIN_EXPERTISE', to='courses.Domain'),
        ),
    ]
