# Generated by Django 3.2.5 on 2021-08-14 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='first_password',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
