# Generated by Django 3.2.5 on 2021-11-01 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistration',
            name='event',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventRegistration',
        ),
    ]
