# Generated by Django 3.2.5 on 2022-02-22 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_remove_member_domain_expertise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='New_domain_expertise',
            new_name='domain_expertise',
        ),
    ]
