# Generated by Django 3.2.5 on 2021-11-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20211106_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='branch',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
