# Generated by Django 3.2.5 on 2021-11-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_member_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='codechef',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='geeksforgeeks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='hackerearth',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
