# Generated by Django 3.2.5 on 2021-11-06 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20211106_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='first_password',
        ),
    ]
