# Generated by Django 3.2.5 on 2021-11-06 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_remove_member_first_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='username',
        ),
    ]
