# Generated by Django 3.2.5 on 2021-11-06 17:34

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_remove_member_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='password',
        ),
        migrations.AddField(
            model_name='member',
            name='domain',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='registration_number',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='skills',
            field=django_mysql.models.ListCharField(models.CharField(max_length=40), default='DSA', max_length=1050, size=20),
            preserve_default=False,
        ),
    ]
