# Generated by Django 3.2.5 on 2021-11-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_auto_20211106_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
