# Generated by Django 3.2.5 on 2021-11-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_member_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='year_of_passing',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
