# Generated by Django 3.2.5 on 2021-11-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_member_year_of_passing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
