# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - enigmavssut-dev

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    if: github.repository == 'EnigmaVSSUT/EnigmaCMS-Backend'
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{secrets.DEV_DATABASE_URL}}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: install, build, and test
        run: |
          yarn

      - name: run migrations
        run: yarn migrate:deploy 

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: |
            .
            !node_modules

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'enigmavssut-dev'
          slot-name: 'Production'
          publish-profile: ${{ secrets.DEV_AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .
